import React from 'react';
import Link from 'next/link';
import { CLASS_SUBJECTS, SUBJECT_DETAILS } from '@/lib/subjects';
import { getPreferredClass } from '@/lib/studentClass';
export const revalidate=0;
export default async function SubjectsPage(){
 const preferred=await getPreferredClass(); const levels=preferred?[preferred,...[9,10,11,12].filter(n=>n!==preferred)]:[9,10,11,12];
 return <div className="page-shell"><div className="page-intro"><div><h1 className="font-display">Subjects, arranged by class.</h1><p>The archive keeps the subject list simple. Classes 9–10 cover Mathematics, Science, Social Science, English, Hindi and Urdu; Classes 11–12 in this archive cover Mathematics, Biology, Physics, Chemistry and English.</p></div><div className="page-note">JKBOSE’s senior-secondary syllabus contains many stream and elective combinations; ARCHIVUM shows the subjects currently supported by this archive.</div></div><div className="mt-12 space-y-14">{levels.map(level=><section key={level}><div className="flex items-end justify-between gap-4 mb-5"><div><h2 className="font-display text-3xl">Class {level}</h2><p className="text-sm mt-1" style={{color:'var(--ink-muted)'}}>{CLASS_SUBJECTS[level as keyof typeof CLASS_SUBJECTS].length} subjects in the current archive</p></div><Link href={`/notes?class=${level}`} className="text-sm font-medium" style={{color:'var(--accent)'}}>Open notes</Link></div><div className="subject-list">{CLASS_SUBJECTS[level as keyof typeof CLASS_SUBJECTS].map(subject=>{const detail=SUBJECT_DETAILS[subject];return <Link key={subject} href={`/notes?class=${level}&subject=${encodeURIComponent(subject)}`} className="subject-row"><h3>{subject}</h3><p>{detail?.description}</p><div className="mt-5 text-xs font-medium" style={{color:'var(--accent)'}}>Open notes</div></Link>})}</div></section>)}</div></div>;
}
