import React from 'react';
import Link from 'next/link';
import { getResources, getRealStats } from '@/lib/resources';
import { getPreferredClass } from '@/lib/studentClass';
import ResourceCard from '@/components/ResourceCard';
import HomeClient from './HomeClient';
import { Archive, ArrowRight, BookOpen, FileText, Lightbulb, Upload, Sparkles, Layers3 } from 'lucide-react';
import { subjectsForClass, SUBJECT_DETAILS } from '@/lib/subjects';

export const revalidate=30;

export default async function HomePage({ searchParams }: { searchParams: Promise<{ class?: string }> }){
 const params = await searchParams;
 const preferred=await getPreferredClass();
 const requestedClass = params.class ? Number(params.class) : undefined;
 const activeClass = [9,10,11,12].includes(requestedClass || 0) ? requestedClass as number : preferred || 10;
 const classForQuery = activeClass;
 const [featured,recent,stats]=await Promise.all([
   getResources({featured:true,class_level:classForQuery,limit:3}),
   getResources({sortBy:'newest',class_level:classForQuery,limit:3}),
   getRealStats(),
 ]);
 return <div className="pb-24 space-y-14 sm:space-y-20">
   <section className="relative overflow-hidden" style={{background:'var(--hero-gradient)'}}>
     <div className="absolute inset-0 opacity-30" style={{backgroundImage:'radial-gradient(circle at 20% 30%, color-mix(in srgb,var(--accent) 45%,transparent), transparent 26%), radial-gradient(circle at 85% 60%, color-mix(in srgb,var(--accent) 35%,transparent), transparent 24%)'}}/>
     <div className="relative max-w-7xl mx-auto px-4 sm:px-6 py-14 sm:py-20 lg:py-24 grid lg:grid-cols-[1.15fr_.85fr] gap-10 items-end">
       <div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.18em]" style={{borderColor:'color-mix(in srgb,var(--accent) 45%,white 20%)',color:'var(--accent-on-hero)',background:'color-mix(in srgb,var(--surface) 8%,transparent)'}}><Sparkles className="w-3.5 h-3.5"/> Class {activeClass} archive</div><h1 className="font-display font-bold text-5xl sm:text-6xl lg:text-7xl leading-[.95] tracking-[-.04em] mt-6" style={{color:'var(--hero-ink)'}}>Everything you need.<br/><span style={{color:'var(--accent-on-hero)',opacity:.62}}>One archive.</span></h1><p className="text-sm sm:text-base max-w-xl mt-6 leading-relaxed" style={{color:'var(--hero-muted)'}}>ARCHIVUM keeps SJS notes, previous papers, study material and exam tips organised around your class—so you spend less time hunting and more time studying.</p><div className="mt-7 max-w-2xl"><HomeClient initialSearch=""/></div></div>
       <div className="hidden lg:block"><div className="relative rounded-[2rem] border p-6 overflow-hidden premium-shadow" style={{background:'color-mix(in srgb,var(--surface) 9%,transparent)',borderColor:'color-mix(in srgb,var(--accent) 35%,transparent)',backdropFilter:'blur(18px)'}}><div className="flex items-center justify-between"><div className="w-12 h-12 rounded-2xl flex items-center justify-center" style={{background:'var(--accent)',color:'var(--accent-contrast)'}}><Archive className="w-6 h-6"/></div><span className="text-[10px] uppercase tracking-[.18em] font-bold" style={{color:'var(--hero-muted)'}}>LIVE LIBRARY</span></div><div className="mt-12"><div className="text-5xl font-display font-bold" style={{color:'var(--hero-ink)'}}>{stats.classCounts[activeClass]||0}</div><p className="text-xs mt-1" style={{color:'var(--hero-muted)'}}>resources for Class {activeClass}</p></div><div className="mt-8 grid grid-cols-2 gap-2"><div className="rounded-xl p-3" style={{background:'color-mix(in srgb,var(--surface) 10%,transparent)'}}><div className="text-lg font-bold" style={{color:'var(--hero-ink)'}}>{stats.totalDownloads}</div><div className="text-[9px] uppercase tracking-wider" style={{color:'var(--hero-muted)'}}>{stats.totalDownloads === 1 ? 'download' : 'real downloads'}</div></div><div className="rounded-xl p-3" style={{background:'color-mix(in srgb,var(--surface) 10%,transparent)'}}><div className="text-lg font-bold" style={{color:'var(--hero-ink)'}}>{stats.totalViews}</div><div className="text-[9px] uppercase tracking-wider" style={{color:'var(--hero-muted)'}}>{stats.totalViews === 1 ? 'view' : 'real views'}</div></div></div></div></div>
     </div>
   </section>

   <section className="archive-section max-w-7xl mx-auto px-4 sm:px-6">
     <div className="rounded-[2rem] border p-6 sm:p-8 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-5" style={{background:'var(--surface)',borderColor:'var(--border)'}}>
       <div><span className="brand-sister text-[10px] uppercase tracking-[.16em]" style={{color:'var(--accent)'}}>SISTER ORGANISATION OF <span className="quest-word">QUEST</span></span><h2 className="font-display font-bold text-2xl mt-1">Meet our sister organisation: SJS Quest</h2><p className="text-xs sm:text-sm mt-2 max-w-2xl" style={{color:'var(--ink-muted)'}}>School stories, magazines, photography and creative work from the SJS community — all in one place.</p></div>
       <a href="https://sjsquest.vercel.app" target="_blank" rel="noopener noreferrer" className="shrink-0 inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-xs font-bold" style={{background:'var(--accent)',color:'var(--accent-contrast)'}}>Visit Quest <ArrowRight className="w-3.5 h-3.5"/></a>
     </div>
   </section>

   <section className="archive-section max-w-7xl mx-auto px-4 sm:px-6 space-y-5"><div className="flex items-end justify-between gap-4"><div><span className="text-[10px] uppercase tracking-[.18em] font-bold" style={{color:'var(--accent)'}}>YOUR STUDY DESK</span><h2 className="font-display font-bold text-2xl sm:text-3xl mt-1">Built around Class {activeClass}</h2></div><Link href={`/tips?class=${activeClass}`} className="text-xs font-bold inline-flex items-center gap-1" style={{color:'var(--accent)'}}>Exam tips <ArrowRight className="w-3.5 h-3.5"/></Link></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Link href={`/notes?class=${activeClass}`} className="group rounded-3xl border p-5 min-h-[150px] flex flex-col justify-between" style={{background:'var(--surface)',borderColor:'var(--border)'}}><div className="w-10 h-10 rounded-2xl flex items-center justify-center" style={{background:'var(--accent-light)',color:'var(--accent)'}}><BookOpen className="w-5 h-5"/></div><div><div className="font-display font-bold text-lg">Notes</div><div className="text-[11px]" style={{color:'var(--ink-muted)'}}>Chapter-wise revision</div></div></Link><Link href={`/previous-papers?class=${activeClass}`} className="group rounded-3xl border p-5 min-h-[150px] flex flex-col justify-between" style={{background:'var(--surface)',borderColor:'var(--border)'}}><div className="w-10 h-10 rounded-2xl flex items-center justify-center" style={{background:'var(--accent-light)',color:'var(--accent)'}}><FileText className="w-5 h-5"/></div><div><div className="font-display font-bold text-lg">Papers</div><div className="text-[11px]" style={{color:'var(--ink-muted)'}}>Past exam practice</div></div></Link><Link href={`/tips?class=${activeClass}`} className="group rounded-3xl border p-5 min-h-[150px] flex flex-col justify-between" style={{background:'var(--surface)',borderColor:'var(--border)'}}><div className="w-10 h-10 rounded-2xl flex items-center justify-center" style={{background:'var(--accent-light)',color:'var(--accent)'}}><Lightbulb className="w-5 h-5"/></div><div><div className="font-display font-bold text-lg">Tips</div><div className="text-[11px]" style={{color:'var(--ink-muted)'}}>Random exam playbook</div></div></Link><Link href="/upload" className="group rounded-3xl border p-5 min-h-[150px] flex flex-col justify-between" style={{background:'var(--accent)',color:'var(--accent-contrast)',borderColor:'var(--accent)'}}><div className="w-10 h-10 rounded-2xl flex items-center justify-center" style={{background:'color-mix(in srgb,var(--surface) 14%,transparent)'}}><Upload className="w-5 h-5"/></div><div><div className="font-display font-bold text-lg">Contribute</div><div className="text-[11px] opacity-75">Share useful material</div></div></Link></div></section>

   <section className="archive-section max-w-7xl mx-auto px-4 sm:px-6 space-y-5">
     <div className="flex items-end justify-between gap-4">
       <div><span className="text-[10px] uppercase tracking-[.18em] font-bold" style={{color:'var(--accent)'}}>CLASS {activeClass} SUBJECTS</span><h2 className="font-display font-bold text-2xl sm:text-3xl mt-1">Choose a subject</h2><p className="text-xs sm:text-sm mt-1" style={{color:'var(--ink-muted)'}}>Your class controls this list, so ARCHIVUM stays focused on what you actually study.</p></div>
       <Link href={`/subjects?class=${activeClass}`} className="hidden sm:inline-flex items-center gap-1 text-xs font-bold" style={{color:'var(--accent)'}}>All subjects <ArrowRight className="w-3.5 h-3.5"/></Link>
     </div>
     <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
       {subjectsForClass(activeClass).map(subject => { const detail = SUBJECT_DETAILS[subject]; return <div key={subject} className="group rounded-3xl border p-4 sm:p-5 min-h-[175px] flex flex-col justify-between transition-all duration-300 hover:-translate-y-1 hover:shadow-xl" style={{background:'var(--surface)',borderColor:'var(--border)'}}>
         <div className="w-11 h-11 rounded-2xl flex items-center justify-center font-display font-bold text-lg" style={{background:'var(--accent-light)',color:'var(--accent)'}}>{detail?.icon || '•'}</div>
         <div><h3 className="font-display font-bold text-base sm:text-lg">{subject}</h3><p className="text-[10px] mt-1" style={{color:'var(--ink-muted)'}}>{detail?.description}</p></div>
         <div className="grid grid-cols-2 gap-2 mt-4">
           <Link href={`/notes?class=${activeClass}&subject=${encodeURIComponent(subject)}`} className="inline-flex items-center justify-center gap-1.5 rounded-xl py-2 text-[10px] font-bold transition-all hover:-translate-y-0.5" style={{background:'var(--accent-light)',color:'var(--accent)'}}><BookOpen className="w-3 h-3"/> Notes</Link>
           <Link href={`/previous-papers?class=${activeClass}&subject=${encodeURIComponent(subject)}`} className="inline-flex items-center justify-center gap-1.5 rounded-xl py-2 text-[10px] font-bold border transition-all hover:-translate-y-0.5" style={{background:'var(--surface-raised)',borderColor:'var(--border)',color:'var(--ink-muted)'}}><FileText className="w-3 h-3"/> PYQs</Link>
         </div>
       </div> })}
     </div>
   </section>

   <section className="archive-section max-w-7xl mx-auto px-4 sm:px-6 space-y-5"><div className="flex items-end justify-between"><div><span className="text-[10px] uppercase tracking-[.18em] font-bold" style={{color:'var(--ink-faint)'}}>CURATED</span><h2 className="font-display font-bold text-2xl sm:text-3xl mt-1">Featured for you</h2></div><Link href={`/notes?class=${activeClass}`} className="text-xs font-bold inline-flex items-center gap-1" style={{color:'var(--accent)'}}>View library <ArrowRight className="w-3.5 h-3.5"/></Link></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{featured.items.map(r=><ResourceCard key={r.id} resource={r}/>)}</div></section>

   <section className="archive-section max-w-7xl mx-auto px-4 sm:px-6"><div className="rounded-[2rem] p-6 sm:p-8 border" style={{background:'var(--accent-light)',borderColor:'color-mix(in srgb,var(--accent) 20%,var(--border))'}}><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-6"><div><span className="text-[10px] font-bold uppercase tracking-[.18em]" style={{color:'var(--accent)'}}>RECENTLY ADDED</span><h2 className="font-display font-bold text-2xl mt-1">Fresh into the Class {activeClass} archive</h2><p className="text-xs mt-2 max-w-xl" style={{color:'var(--ink-muted)'}}>New material is reviewed before publication. Real views, downloads and ratings are shown without inflated placeholders.</p></div><Link href={`/search?class=${activeClass}`} className="shrink-0 inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-xs font-bold" style={{background:'var(--accent)',color:'var(--accent-contrast)'}}>Explore all <ArrowRight className="w-3.5 h-3.5"/></Link></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-7">{recent.items.map(r=><ResourceCard key={r.id} resource={r}/>)}</div></div></section>
 </div>;
}
