'use client';
import React,{useMemo,useState} from 'react';
import { Check, Lightbulb, RefreshCw, Send, ShieldCheck } from 'lucide-react';
import type { Tip } from '@/lib/tips';

export default function TipsClient({initialTips,initialClass}:{initialTips:Tip[];initialClass:number}){
 const [tips,setTips]=useState(initialTips); const [classLevel,setClassLevel]=useState(initialClass); const [title,setTitle]=useState(''); const [body,setBody]=useState(''); const [author,setAuthor]=useState(''); const [status,setStatus]=useState(''); const [sending,setSending]=useState(false);
 const refresh=async()=>{const r=await fetch(`/api/tips?class=${classLevel}`);if(r.ok){const j=await r.json();setTips(j.tips||[]);}};
 const shuffled=useMemo(()=>[...tips].sort(()=>Math.random()-.5),[tips]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSending(true);setStatus('');try{const r=await fetch('/api/tips',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({class_level:classLevel,title,body,author})});const j=await r.json();if(!r.ok)throw new Error(j.error);setTitle('');setBody('');setAuthor('');setStatus('Submitted — it will appear after moderation.');}catch(e){setStatus(e instanceof Error?e.message:'Could not submit tip.')}finally{setSending(false)}};
 return <div className="space-y-8"><div className="flex flex-col sm:flex-row gap-3 sm:items-center justify-between rounded-2xl border p-4" style={{background:'var(--surface)',borderColor:'var(--border)'}}><div className="flex items-center gap-2 text-xs font-bold"><span className="w-8 h-8 rounded-xl flex items-center justify-center" style={{background:'var(--accent-light)',color:'var(--accent)'}}><Lightbulb className="w-4 h-4"/></span>Showing random tips for Class {classLevel}</div><div className="flex gap-2">{[9,10,11,12].map(level=><button key={level} onClick={async()=>{setClassLevel(level);const r=await fetch(`/api/tips?class=${level}`);if(r.ok){const j=await r.json();setTips(j.tips||[])}}} className="px-3 py-2 rounded-xl text-[11px] font-bold border" style={{borderColor:level===classLevel?'var(--accent)':'var(--border)',background:level===classLevel?'var(--accent-light)':'var(--surface-raised)',color:level===classLevel?'var(--accent)':'var(--ink-muted)'}}>{level}</button>)}<button onClick={refresh} className="w-9 h-9 rounded-xl border flex items-center justify-center" style={{borderColor:'var(--border)'}} aria-label="Refresh tips"><RefreshCw className="w-3.5 h-3.5"/></button></div></div>
 <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{shuffled.slice(0,9).map((tip,i)=><article key={tip.id} className="rounded-3xl border p-5 sm:p-6 min-h-[180px] relative overflow-hidden" style={{background:'var(--surface)',borderColor:'var(--border)'}}><div className="absolute -right-8 -top-8 w-24 h-24 rounded-full" style={{background:'var(--accent-light)'}}/><div className="relative"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[.16em]" style={{color:'var(--accent)'}}>TIP {String(i+1).padStart(2,'0')}</span><ShieldCheck className="w-4 h-4" style={{color:'var(--accent)'}}/></div><h2 className="font-display font-bold text-lg mt-6">{tip.title}</h2><p className="text-sm leading-relaxed mt-2" style={{color:'var(--ink-muted)'}}>{tip.body}</p><p className="text-[10px] font-semibold mt-5" style={{color:'var(--ink-faint)'}}>— {tip.author||'SJS student'}</p></div></article>)}</div>
 <section className="rounded-[2rem] border p-6 sm:p-8" style={{background:'var(--accent)',color:'var(--accent-contrast)',borderColor:'var(--accent)'}}><div className="max-w-2xl"><span className="text-[10px] font-bold uppercase tracking-[.2em] opacity-70">COMMUNITY PLAYBOOK</span><h2 className="font-display font-bold text-2xl sm:text-3xl mt-2">Know a tip that actually works?</h2><p className="text-xs sm:text-sm mt-2 opacity-80">Add a short, class-specific exam tip. Keep it useful, original and under 600 characters.</p><form onSubmit={submit} className="mt-6 space-y-3"><div className="grid sm:grid-cols-2 gap-3"><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} placeholder="Tip title" className="rounded-xl px-3.5 py-3 text-xs outline-none" style={{background:'color-mix(in srgb,var(--surface) 12%,transparent)',color:'inherit',border:'1px solid color-mix(in srgb,currentColor 18%,transparent)'}}/><input value={author} onChange={e=>setAuthor(e.target.value)} maxLength={80} placeholder="Your name (optional)" className="rounded-xl px-3.5 py-3 text-xs outline-none" style={{background:'color-mix(in srgb,var(--surface) 12%,transparent)',color:'inherit',border:'1px solid color-mix(in srgb,currentColor 18%,transparent)'}}/></div><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={600} rows={4} placeholder="Write the tip…" className="w-full rounded-xl px-3.5 py-3 text-xs outline-none resize-none" style={{background:'color-mix(in srgb,var(--surface) 12%,transparent)',color:'inherit',border:'1px solid color-mix(in srgb,currentColor 18%,transparent)'}}/><div className="flex flex-col sm:flex-row gap-3 sm:items-center"><button disabled={sending} className="inline-flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-xs font-bold" style={{background:'var(--surface)',color:'var(--ink)'}}><Send className="w-3.5 h-3.5"/>{sending?'Submitting…':'Submit tip'}</button><span className="text-[10px] opacity-70 flex items-center gap-1"><Check className="w-3 h-3"/> Moderated before publishing</span></div>{status&&<p className="text-xs mt-2 opacity-90">{status}</p>}</form></div></section>
 </div>;
}
